Update bash_template to include initial version check

diff --git a/bash_template b/bash_template
--- a/bash_template
+++ b/bash_template
@@ -11,9 +11,22 @@
 #:              : 1 General Failure (varied message)
 #:              : 3 Bash-4.0+ is required to run this script
 ################ Script metadata ###############################################
-#strict mode (http://redsymbol.net/articles/unofficial-bash-strict-mode/)
+
+# strict mode
+# http://redsymbol.net/articles/unofficial-bash-strict-mode/
+# https://disconnected.systems/blog/another-bash-strict-mode/
 set -euo pipefail
-#IFS=$'\n\t'
+IFS=$'\n\t'
+# shellcheck disable=SC2154
+trap 's=$?; echo "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR
+
+# Version Check
+if ((BASH_VERSINFO < 4))
+then
+  printf "Bash-4.0+ is required to run this script \\n" >&2
+  exit 3
+fi
+
 
 #Function
 function die() {
@@ -39,10 +52,8 @@ function output() {
   return
 }
 
-if ((BASH_VERSINFO[0] > 4))
-then
-  fail 3 "Bash-4.0+ is required to run this script"
-fi
- 
+# <-- User Functions here-->
+
+
 # <-- Main Code Here -- >
 exit 0
